/**
 * Design System CSS Generator
 * Lê tokens.ts e gera variáveis CSS em globals.css
 *
 * Uso: npm run tokens
 */

import * as fs from "fs";
import * as path from "path";
import { tokens } from "./tokens";
import { hexToHSL } from "./utils";

function generateCSSVariables(
  colors: Record<string, string>,
  indent: string = "  "
): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(colors)) {
    const cssKey = key.replace(/([A-Z])/g, "-$1").toLowerCase();
    const hsl = hexToHSL(value);
    lines.push(`${indent}--${cssKey}: ${hsl};`);
  }
  return lines.join("\n");
}

function generateCSS(): string {
  const lightVars = generateCSSVariables(tokens.colors.light);
  const darkVars = generateCSSVariables(tokens.colors.dark);

  return `/*
 * AUTO-GENERATED by design-system/generate-css.ts
 * NÃO edite manualmente — edite tokens.ts e rode: npm run tokens
 * Gerado em: ${new Date().toISOString()}
 */

@import "tailwindcss";

:root {
${lightVars}
  --radius: ${tokens.borderRadius.lg};
}

.dark {
${darkVars}
}

@theme inline {
  --color-background: hsl(var(--background));
  --color-foreground: hsl(var(--foreground));
  --color-card: hsl(var(--card));
  --color-card-foreground: hsl(var(--card-foreground));
  --color-popover: hsl(var(--popover));
  --color-popover-foreground: hsl(var(--popover-foreground));
  --color-primary: hsl(var(--primary));
  --color-primary-foreground: hsl(var(--primary-foreground));
  --color-secondary: hsl(var(--secondary));
  --color-secondary-foreground: hsl(var(--secondary-foreground));
  --color-muted: hsl(var(--muted));
  --color-muted-foreground: hsl(var(--muted-foreground));
  --color-accent: hsl(var(--accent));
  --color-accent-foreground: hsl(var(--accent-foreground));
  --color-destructive: hsl(var(--destructive));
  --color-destructive-foreground: hsl(var(--destructive-foreground));
  --color-success: hsl(var(--success));
  --color-success-foreground: hsl(var(--success-foreground));
  --color-warning: hsl(var(--warning));
  --color-warning-foreground: hsl(var(--warning-foreground));
  --color-border: hsl(var(--border));
  --color-input: hsl(var(--input));
  --color-ring: hsl(var(--ring));
  --color-surface: hsl(var(--surface));
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-family: ${tokens.typography.fontFamily.sans};
  }
}
`;
}

// Execute
const cssContent = generateCSS();
const outputPath = path.resolve(__dirname, "../app/globals.css");
fs.writeFileSync(outputPath, cssContent, "utf-8");
console.log("✅ globals.css generated successfully at:", outputPath);
console.log(`   Light mode: ${Object.keys(tokens.colors.light).length} variables`);
console.log(`   Dark mode: ${Object.keys(tokens.colors.dark).length} variables`);
